### ISSUE TITLE
Why the sin and exp time varying function is taken? 

### ISSUE THREAD

**Issue by neetu5510** [bhaskatripathi/GWOSVR#1]
Why the sin and exp time varying function is taken? Can we take some other functions as well? How have you selected the coefficient values in the function? Is there any paper for reference?

**Comment by bhaskatripathi** [comment]
It is taken to add a sinusoidal perturbation in the overall velocity equation. The value of the perturbation decreases as the iterations progress. you can refer the DMP-PSO paper by Kundu et al.
Refer this one also : https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7669709

**Comment by bhaskatripathi** [comment]
Closing the issue
